<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Announcement PDF</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #333; padding: 5px; text-align: left; }
        th { background: #eee; }
        .header { margin-bottom: 10px; }
        .footer { margin-top: 20px; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Announcements List</h2>
        <p>Printed by: {{ $printedBy }}</p>
        <p>Date: {{ $date }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>content</th>
                <th>Publish date</th>
                <th>Expire date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($announcements as $index => $announcement)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $announcement->content }}</td>
                <td>{{ $announcement->created_at->format('Y-m-d') }}</td>
                <td>{{ $announcement->expires_at }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by SDMS</p>
    </div>
</body>
</html>
