<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Quotes PDF</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #333; padding: 5px; text-align: left; }
        th { background: #eee; }
        .header { margin-bottom: 10px; }
        .footer { margin-top: 20px; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Quotes List</h2>
        <p>Printed by: {{ $printedBy }}</p>
        <p>Date: {{ $date }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Company</th>
                <th>Client</th>
                <th>Quote #</th>
                <th>Total</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($quotes as $index => $quote)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $quote->company_name }}</td>
                <td>{{ $quote->client_name }}</td>
                <td>{{ $quote->quote_number }}</td>
                <td>${{ number_format($quote->grand_total, 2) }}</td>
                <td>{{ $quote->created_at->format('d M Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by <b>DevTrack System<b></p>
    </div>
</body>
</html>
